### PR TITLE
Added GitHub insights stack quickstart

### PR DESCRIPTION
**Pull request by utsavbhattarai007**
Done #26 

- **Airbyte Setup**: Configured GitHub as the data source and BigQuery as the destination for raw data extraction.

- **dbt Transformation**: Created models (code_quality, collaboration_patterns, project_health).

- **Dagster Orchestration**: Established a Dagster pipeline to manage the data flow from Airbyte extraction to dbt transformation.

### CODE REVIEW

**Comment by ThaliaBarrera** [comment]
This looks amazing @utsavbhattarai007! 

Just a small detail: Could you include a screenshot of the Dagster DAG in the README so people will know what they will build with this quickstart? Or a simple architecture diagram. (Check other merged quickstarts).

**Comment by utsavbhattarai007** [comment]
Ok, I will

**Comment by utsavbhattarai007** [comment]
@ThaliaBarrera Added the architecture diagram

**Comment by ThaliaBarrera** [comment]
Closes #26

**Pull request merged**
