### PR TITLE
Added ticket volume analytics stack

### LINKED ISSUE #34: Ticket Volume Analysis Stack
### Analyzing Support Ticket Volume with Zendesk Data.

Leverage Airbyte to extract ticket data from Zendesk, transform the data using dbt, and analyze ticket volumes, patterns, and trends to optimize support operations and resource allocation.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

### PR DESCRIPTION
**Pull request by bishalbera**
Closes #34 

- Made a connection between Zendesk Support and BigQuery using Airbyte 's Terraform provider.
- Used DBT to transform data and  perform some analysis.
- Used Dagster to perform testing and monitor data pipelines.

### CODE REVIEW

**Review by ThaliaBarrera — APPROVED** [review]
Looks great @bishalbera! 🔥 I love the dbt models you included

**Comment by bishalbera** [comment]
@ThaliaBarrera Thanks. Actually I also wanted to setup looker But my trial got ended yesterday 😢

**Comment by ThaliaBarrera** [comment]
Oh, that's a shame @bishalbera, it would have been nice to have! Maybe you could try with an open source tool like Metabase or Superset?

**Comment by ThaliaBarrera** [comment]
@bishalbera unfortunately I don't have a good doc right now! I'll try to implement it myself in a quickstart and share it with you :).

**Comment by bishalbera** [comment]
@ThaliaBarrera ok ty

**Pull request merged**
