### PR TITLE
RAG quickstart using Airbyte Cloud, S3, and Pinecone using dbt, terraform and queried using open ai LLM

### PR DESCRIPTION
**Pull request by btkcodedev**
Resolves: https://github.com/airbytehq/PyAirbyte-Hackathon/issues/14

## Dataflow
Fetch data from S3 and pass it to big query for transformation if necessary and pass big query data to pinecone for LLM querying
All details are mentioned in the [README.md](https://github.com/airbytehq/quickstarts/blob/btkcodedev/pyairbyte_s3_rag/airbyte_s3_pinecone_rag/README.md) (live preview link) of the quickstart.

image

### CODE REVIEW

**Comment by btkcodedev** [comment]
@bindipankhudi ,its ready for review

**Comment by bindipankhudi** [comment]
That is great @btkcodedev! I will review this on Monday (Pacific time). Please feel free to pick another ticket to work on.

**Comment by btkcodedev** [comment]
@bindipankhudi Thank you!

**Comment by btkcodedev** [comment]
@bindipankhudi, @aaronsteers
Any update here?

**Comment by bindipankhudi** [comment]
@btkcodedev thank you for your patience. It's been assigned to @aaronsteers for review. He has been super busy, so I expect this should be done by EOW.

**Comment by btkcodedev** [comment]
Thank You!!

**Review by aaronsteers — CHANGES_REQUESTED** [review]
@btkcodedev - This is a large PR and with a lot of complexity. Thanks for your hard work on this.

I especially appreciate the detailed walkthrough in the `README`, the inclusion of the data flow diagram, and the inclusion of the `.env.template` file.

One piece of feedback we can apply before merging would be to see if we can remove some of the boilerplate dbt files without breaking the project execution. Specifically, I think we could remove some/most of the `.gitkeep` files preserving folders for unused dbt functionality. And the `models/example` folder contents (I think) are not used.

image

Once these small changes are incorporated, I think this PR is ready to go. 🚀

**Comment by btkcodedev** [comment]
@aaronsteers Done!!
Thanks!! :bow:

**Pull request merged**
