### PR TITLE
Added Customer Segmentation Analytics Stack

### LINKED ISSUE #17: Customer Segmentation Stack
### Building Customer Segments with E-commerce Data.

Extract customer interaction and transaction data from e-commerce platforms using Airbyte and dbt to create detailed customer segments for personalized marketing.

How to get started: 

- Check out the [README](https://github.com/airbytehq/quickstarts/tree/main) and the [Contribution instructions](https://github.com/airbytehq/quickstarts/blob/main/CONTRIBUTING.md) in this repo.
- Check one of the [existing quickstarts](https://github.com/airbytehq/quickstarts#list-of-available-quickstarts) and observe their structure.
- (Optional, but highly recommended) Implement one of the quickstarts by following the instructions in their README. I recommend starting with [E-commerce analytics in BigQuery](https://github.com/airbytehq/quickstarts/tree/main/ecommerce_analytics_bigquery)

### PR DESCRIPTION
**Pull request by bishalbera**
Closes #17 

`I have created Python scripts for data visualization, but the second and third plots are not displaying because I don't have any customers for my Shopify store. I followed the Airbyte documentation to obtain the API key for Shopify. However, I'm unable to show the charts at the moment due to the lack of customers for my store. That's why I couldn't attach screenshots of the charts.`

`(venv) PS C:\Users\bisha\quickstarts\customer_segmentation_analytics_shopify\dbt_project\analyses> python purchase_pattern_segmentation_analysis.py 
Traceback (most recent call last):
  File "C:\Users\bisha\quickstarts\customer_segmentation_analytics_shopify\dbt_project\analyses\purchase_pattern_segmentation_analysis.py", line 52, in <module>
    segments, counts = zip(*segment_counts.items())
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
(venv) PS C:\Users\bisha\quickstarts\customer_segmentation_analytics_shopify\dbt_project\analyses> python rfm_segmentation_analysis.py
Traceback (most recent call last):
  File "C:\Users\bisha\quickstarts\customer_segmentation_analytics_shopify\dbt_project\analyses\rfm_segmentation_analysis.py", line 54, in <module>       
    segments, counts = zip(*segment_counts.items())
    ^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)`

I am getting this error for the last two python scripts which indicates that I dont have any active customer. @ThaliaBarrera what should I do?? 😢

### CODE REVIEW

**Comment by ThaliaBarrera** [comment]
@bishalbera I think we can get you credentials so you can test. Could you DM @marcosmarxm on Slack with your email and mention you'd like Shopify credentials for the hackathon? Hopefully it will work!

**Comment by bishalbera** [comment]
@ThaliaBarrera No, I've followed [this](https://docs.airbyte.com/integrations/sources/shopify) and obtained the credentials. However, the issue is that, following those steps, I've created a store, but there are no active customers in my store, which is why I was getting the error. I believe that when a real user follows these steps and has their customers, it will work fine.

**Comment by ThaliaBarrera** [comment]
> @ThaliaBarrera No, I've followed [this](https://docs.airbyte.com/integrations/sources/shopify) and obtained the credentials. However, the issue is that, following those steps, I've created a store, but there are no active customers in my store, which is why I was getting the error. I believe that when a real user follows these steps and has their customers, it will work fine.

Got it @bishalbera! I was thinking that maybe we had a test account with customers. But we can merge this for now! It looks good.

**Comment by bishalbera** [comment]
@ThaliaBarrera Tysm got a relief 😅 . Now I can focus on the new issuue.

**Pull request merged**
